
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'HKitDemo' do
    
    # objective-c
    pod 'HKit', :path => '../'
    
    target 'HKitDemoTests' do
      inherit! :search_paths
    end
    
    target 'HKitDemoUITests' do
      inherit! :search_paths
    end
end
